FROM nginx
MAINTAINER Kiryanenko Alexander <KiryanenkoAV@gmail.com>

ENV RAILS_ROOT /var/www/app
WORKDIR $RAILS_ROOT

COPY public public/
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD nginx -g 'daemon off;'
