version: '2'

services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: smartparking
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:3.2-alpine
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  web:
    depends_on:
      - postgres
      - redis
    volumes:
      - public:/app/public
    build: .
    ports:
      - 3000:3000
    env_file: .env
    environment:
      RAILS_ENV: production
    links:
      - postgres
      - redis

  nginx:
    image: nginx
    volumes_from:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    ports:
      - 80:80
    links:
      - web

volumes:
  redis:
  postgres:
  public:
