version: '3'

services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: smartparking
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:3.2-alpine
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  web:
    depends_on:
      - postgres
      - redis
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env

  nginx:
    image: nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    command: nginx -g 'daemon off;'
    ports:
    - 80:80

volumes:
  redis:
  postgres: