version: '2'

services:
  postgres:
    image: mdillon/postgis:9.6-alpine
    environment:
      POSTGRES_USER: smartparking
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    restart: always

  mqtt:
    image: ansi/mosquitto
    ports:
      - 1883:1883
    restart: always

  memcached:
      image: memcached:alpine
      ports:
        - 11211:11211

  web:
    depends_on:
      - postgres
      - redis
      - mqtt
      - memcached
    volumes:
      - public:/app/public
      - tmp:/tmp
    build: .
    ports:
      - 3000:3000
    env_file: .env
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://redis:6379/1
      MQTT_URI: mqtt://mqtt
      DB_HOST: postgres
    links:
      - postgres
      - redis
      - mqtt
      - memcached
    restart: always

  nginx:
    image: nginx:alpine
    volumes_from:
      - web
    volumes:
      - ./config/nginx.conf.erb:/etc/nginx/nginx.conf
      - nginx_logs:/etc/nginx/logs/nginx
    depends_on:
      - web
    ports:
      - 80:80
    links:
      - web
    restart: always

volumes:
  redis:
  postgres:
  public:
  tmp:
  nginx_logs:
